const config = {
	"keyValue":"",
	"generations":{
		"number":6,
		"label":["1期生","2期生","3期生","4期生","5期生","OG"],
		"info":[
			{
				id:0,
				label:"1期生",
				is_ready:false,
			},
			{
				id:1,
				label:"2期生",
				is_ready:false,
			},
			{
				id:2,
				label:"3期生",
				is_ready:false,
			},
			{
				id:3,
				label:"4期生",
				is_ready:false,
			},
			{
				id:4,
				label:"5期生",
				is_ready:true,
			},
			{
				id:5,
				label:"OG",
				is_ready:false,
			},]},

	"typing_data":{
		"total":10,
		"member":{
			"fifth":[
		{
			id:0,
			src:"/image/fifth/aruno.jpeg",
			name:"中西アルノ",
			kana:"なかにしあるの",
			alphabet:"nakanishiaruno",
		},
		{
			id:1,
			src:"/image/fifth/ioki.jpeg",
			name:"五百城茉央",
			kana:"いおきまお",
			alphabet:"iokimao",
		},
		{
			id:2,
			src:"/image/fifth/nagi.jpeg",
			name:"井上和",
			kana:"いのうえなぎ",
			alphabet:"inouenagi",
		},
		{
			id:3,
			src:"/image/fifth/tomisato.jpeg",
			name:"冨里奈央",
			kana:"とみさとなお",
			alphabet:"tomisatonao",
		},
		{
			id:4,
			src:"/image/fifth/ichinose.jpeg",
			name:"一ノ瀬美空",
			kana:"いちのせみく",
			alphabet:"ichinosemiku",
		},
		{
			id:5,
			src:"/image/fifth/sugawara.jpeg",
			name:"菅原咲月",
			kana:"すがわらさつき",
			alphabet:"sugawarasatsuki",
		},
		{
			id:6,
			src:"/image/fifth/ogawa.jpeg",
			name:"小川彩",
			kana:"おがわあや",
			alphabet:"ogawaaya",
		},
		{
			id:7,
			src:"/image/fifth/okuda.jpeg",
			name:"奥田いろは",
			kana:"おくだいろは",
			alphabet:"okudairoha",
		},
		{
			id:8,
			src:"/image/fifth/ikeda.jpeg",
			name:"池田瑛紗",
			kana:"いけだてれさ",
			alphabet:"ikedateresa",
		},
		{
			id:9,
			src:"/image/fifth/kawasaki.jpeg",
			name:"川﨑桜",
			kana:"かわさきさくら",
			alphabet:"kawasakisakura",
		},
		{
			id:10,
			src:"/image/fifth/okamoto.jpeg",
			name:"岡本姫奈",
			kana:"おかもとひな",
			alphabet:"okamotohina",
		},],


		},
	},
	"sample_data":[
		{
			id:0,
			src:"/image/fifth/aruno.jpeg",
			name:"中西アルノ",
			kana:"なかにしあるの",
			alphabet:"nakanishiaruno",
		},
		{
			id:1,
			src:"/image/fifth/ioki.jpeg",
			name:"五百城茉央",
			kana:"いおきまお",
			alphabet:"iokimao",
		},
		{
			id:2,
			src:"/image/fifth/nagi.jpeg",
			name:"井上和",
			kana:"いのうえなぎ",
			alphabet:"inouenagi",
		},
		{
			id:3,
			src:"/image/fifth/tomisato.jpeg",
			name:"冨里奈央",
			kana:"とみさとなお",
		},
		{
			id:4,
			src:"/image/fifth/ichinose.jpeg",
			name:"一ノ瀬美空",
			kana:"いちのせみく",
		},
		{
			id:5,
			src:"/image/fifth/sugawara.jpeg",
			name:"菅原咲月",
			kana:"すがわらさつき",
		},
		{
			id:6,
			src:"/image/fifth/ogawa.jpeg",
			name:"小川彩",
			kana:"おがわあや",
		},
		{
			id:7,
			src:"/image/fifth/okuda.jpeg",
			name:"奥田いろは",
			kana:"おくだいろは",
		},
		{
			id:8,
			src:"/image/fifth/ikeda.jpeg",
			name:"池田瑛紗",
			kana:"いけだてれさ",
		},
		{
			id:9,
			src:"/image/fifth/kawasaki.jpeg",
			name:"川﨑桜",
			kana:"かわさきさくら",
		},
		{
			id:10,
			src:"/image/fifth/okamoto.jpeg",
			name:"岡本姫奈",
			kana:"おかもとひな",
		},],

	"idToName":[{"0":"iokimao"}],

};


export default config;
